### ISSUE TITLE
회식 있습니다.

### ISSUE THREAD

**Issue by jake5113** [jake5113/TeamProject#3]
왕십리 하남돼지

**Comment by kof99athena** [comment]
하남돼지는 예전보다 맛이 없어졌어요
https://map.naver.com/v5/entry/place/1814052949?lng=127.032318162159&lat=37.562520710798495&placePath=%2Fhome
육감식당이 맛있어요 

https://map.naver.com/v5/entry/place/1881901392?lng=127.030222&lat=37.5638346&placePath=%2Fhome&c=15,0,0,0,dh
여기는 조용하고 깔끔해요
